### PR TITLE
add metadafilter option

### PR DESCRIPTION
**Pull request by ivanovv**
This PR is a combination of @lasseebert changes done here https://github.com/lasseebert/logger_papertrail_backend/compare/master...lasseebert:overwrite_system_name  and `metadata_filter`, copied from https://github.com/onkel-dirtus/logger_file_backend

Sorry, no tests :-/

### CODE REVIEW

**Comment by larskrantz** [comment]
Thank's @ivanovv and @lasseebert - well done! 
I'm sorry for the delay, there's more `:queue.in/2` than `:queue.out/1` at work. I'll release a version as soon as possible.

**Comment by larskrantz** [comment]
This PR is present in hex.pm as version 1.1.0. 
Again, thanks!

**Comment by lasseebert** [comment]
Awesome, thanks 🙂

**Comment by ivanovv** [comment]
Thanks @lasseebert @larskrantz !

**Pull request merged**
